const MAX_DESCRIPTION_LENGTH = 200
const MAX_NICKNAME_LENGTH = 15
const PROFILE_DOT_REPLACEMENT = "-"
const RECENT_BOOK_DAYS_INTERVAL = 1

export {
  MAX_DESCRIPTION_LENGTH,
  MAX_NICKNAME_LENGTH,
  PROFILE_DOT_REPLACEMENT,
  RECENT_BOOK_DAYS_INTERVAL,
}
